apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  labels:
    app: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.3
          volumeMounts:
            - name: mongodb-pvc
              mountPath: /data/db
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
    - metadata:
        name: mongodb-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-configmap
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    http.host: 0.0.0.0
    http.cors.enabled: true
    http.cors.allow-origin: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-statefulset
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch-service
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: nakaakist/elasticsearch-growi
          volumeMounts:
            - name: elasticsearch-pvc
              mountPath: /usr/share/elasticsearch/data
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
          ports:
            - containerPort: 9200
          env:
            - name: LimitMEMLOCK
              value: "infinity"
            - name: bootstrap.memory_lock
              value: "false"
            - name: discovery.type
              value: single-node
            - name: xpack.graph.enabled
              value: "false"
            - name: xpack.ml.enabled
              value: "false"
            - name: xpack.monitoring.enabled
              value: "false"
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.watcher.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms100m -Xmx100m"
          resources:
            requests:
              cpu: "200m"
              memory: "0.1Gi"
      volumes:
        - name: config
          configMap:
            name: elasticsearch-configmap
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: growi-service
  labels:
    app: growi
spec:
  selector:
    app: growi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi-deployment
  labels:
    app: growi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growi
  template:
    metadata:
      labels:
        app: growi
    spec:
      initContainers:
        - image: busybox
          command: ["sh", "-c", "until nslookup elasticsearch-service; do echo waiting for elasticsearch-service; sleep 1; done"]
          name: wait-for-elasticsearch
        - image: busybox
          command: ["sh", "-c", "until nslookup mongodb-service; do echo waiting for mongodb-service; sleep 1; done"]
          name: wait-for-mongodb
      containers:
        - name: growi
          image: weseek/growi:4.0.4
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/growi
            - name: ELASTICSEARCH_URI
              value: http://elasticsearch-service:9200/growi
            - name: PASSWORD_SEED
              valueFrom:
                secretKeyRef:
                  name: growi-secrets
                  key: password-seed
