apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: nakaakist/backup-crowi
              env:
                - name: ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: crowi-secrets
                      key: aws-access-key-id
                - name: SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: crowi-secrets
                      key: aws-secret-access-key
                - name: BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: crowi-secrets
                      key: aws-backup-bucket-name
                - name: MONGO_HOST
                  value: mongodb-service
          restartPolicy: OnFailure
